In [5]:
import numpy as np
array=np.array([[[2,3,4],[4,5,6],[7,8,9]]])

In [6]:
array.ndim

3

In [7]:
array.size

9

In [12]:
import numpy as np
user_input = input("Enter space: ")
user_values = [int(x) for x in user_input.split()]
original_array = np.array(user_values)

float_array = original_array.astype(float)
print("Original array:", original_array)
print("Array converted to float type:", float_array)



Enter space: 4
Original array: [4]
Array converted to float type: [4.]


In [15]:
orginal_array=np.array([10,20,30])
apend_value=np.array([40,50,60,70,80,90])
new_array=np.append(orginal_array,apend_value)


In [16]:
print(new_array)

[10 20 30 40 50 60 70 80 90]


In [19]:
array1=np.array([2,3,4])
array2=np.array([2,3,4])
sumarray=array1+array2

In [20]:
sumarray

array([4, 6, 8])

In [25]:
array1=np.arange(10,100,10).reshape(3,3)
array1


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [32]:
array1[0,:]

array([10, 20, 30])

In [34]:
array1[2,2]

90